version: '3'

services:
  postgres:
    image:  awesome/db
    build:
      dockerfile: ./Dockerfile.postgres
    ports:
      - "5400:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ../db_data/postgres:/var/lib/postgresql/data
    

   